spring:
  datasource:
    url: jdbc:h2:mem:cloud_vendor
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect


  jpa.hibernate.ddl_auto: create
  h2:
    console:
      enabled: true